services:
  # Backend API
  - type: web
    name: shopagent-backend
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TAVILY_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.0

  # Frontend
  - type: web
    name: shopagent-frontend
    env: node
    region: oregon
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend/dist && python3 -m http.server $PORT
    envVars:
      - key: VITE_API_URL
        value: https://shopagent-backend.onrender.com

